// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace swingvy.Models
{
    public partial class calendar
    {
        public int calendar_id { get; set; }
        public int member_id { get; set; }
        public DateTime? startTime { get; set; }
        public DateTime? endTime { get; set; }
        public string name { get; set; }

        public virtual member member { get; set; }
    }
}