// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace swingvy.Models
{
    public partial class member
    {
        public member()
        {
            calendar = new HashSet<calendar>();
            leaveOrder = new HashSet<leaveOrder>();
            memberData = new HashSet<memberData>();
            worktime = new HashSet<worktime>();
        }

        public int member_id { get; set; }
        public string account { get; set; }
        public string password { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] Salt { get; set; }

        public virtual ICollection<calendar> calendar { get; set; }
        public virtual ICollection<leaveOrder> leaveOrder { get; set; }
        public virtual ICollection<memberData> memberData { get; set; }
        public virtual ICollection<worktime> worktime { get; set; }
    }
}