// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace swingvy.Models
{
    public partial class memberData
    {
        public int memberData_id { get; set; }
        public int member_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public int type { get; set; }
        public int position { get; set; }
        public int head { get; set; }
        public string img_url { get; set; }

        public virtual member member { get; set; }
    }
}